### PR TITLE
Some improvement in 6_practical_conversion

### PR DESCRIPTION
**Pull request by me-shaon**

### CODE REVIEW

**Comment by davidgatti** [comment]
@me-shaon same variable rename - keep it as is, since the variable name reflect what they are all about.

**Comment by me-shaon** [comment]
Changed back to the previous variable naming.

**Comment by davidgatti** [comment]
I also downloaded your cloned copy of my repo, and so now I see that you are not using Tabs. Make sure you have your IDE set to tabs, because right now you replaced some tabs with spaces :)

**Comment by davidgatti** [comment]
This is also true for all there PR that you made.

**Comment by me-shaon** [comment]
Tab issue fixed.

**Comment by davidgatti** [comment]
Sorry for the radio silence, I've decided to not accept the PRs, because they chain things that are personal preferences. You are welcome to fix typos, but not coding style, because that would be impossible to agree on, I you you'll understand :)

**Pull request closed without merging**
