### PR TITLE
Some improvement in 5_nonempty_custom_stream

### PR DESCRIPTION
**Pull request by me-shaon**

### CODE REVIEW

**Comment by davidgatti** [comment]
I don't like the variable rename, you went form variable name that clearly show what they are about, to a general naming that is not reflecting the state of the variable.

**Comment by me-shaon** [comment]
Ok, i've changed it back to as you are proposing.

**Comment by me-shaon** [comment]
Tab issue fixed.

**Comment by davidgatti** [comment]
Sorry for the radio silence, I've decided to not accept the PRs, because they chain things that are personal preferences. You are welcome to fix typos, but not coding style, because that would be impossible to agree on, I you you'll understand :)

**Pull request closed without merging**
