### PR TITLE
Some bug fixed and Code style improved

### PR DESCRIPTION
**Pull request by me-shaon**
I've improved the code style a bit, although it's just a suggestion, feel free to review it.

### CODE REVIEW

**Comment by davidgatti** [comment]
@me-shaon thank you for the involvement in my article. Sadly I can't accept this PR because you missed the point of what I try to do. I try to teach in the simplest way possible, by making the code as approachable as possible. 

- your comment style is harder to read 
- const vs let is to confusing for people not use to it, plus const is not working the way you think it is working in this case. Const just locks the pointer, not the content.

PR that I will accept are

- typo fixes
- and better sentences. 

If everything else is preserved as is. I hope this make sense :)

**Comment by me-shaon** [comment]
It's ok, the changes were mostly suggestions. Using 'const' vs 'let' and a different comment style is solely a developers preference. Though I didn't really understand what you meant by 'Const just locks the pointer, not the content'. I knew that **const** should be used for the variables/references which will not be *assigned* later by another reference, but the content of the referenced object can be changed.
Like if I write something like: 
`const obj = {}`
I can't write later: `obj = []` or something like this, but i can write: `obj.prop = {}` 
Not sure if that's what you meant, but I tried to follow this concept on my PRs.
However, other than that-
1. I saw some bugs like counting **bytes**, which I tried to fix in [this commit](https://github.com/davidgatti/How-to-Understand-Streams-in-NodeJS/pull/2/commits/2e0a57a8e544d1707f18c3762af3fe07712f1780).
2. Also in some of your files, there are some redundant codes like [this 'options_compressed' variable in this code bit](https://github.com/davidgatti/How-to-Understand-Streams-in-NodeJS/pull/2/commits/d8902c608fda95a6da5d7b1e7c8469fad8921746#diff-1cfdb69e3de4ca4b03d14d3744621d91L25).
3. Variable names are not meaningful in some of your files which I tried to fix in some [commits like this](https://github.com/davidgatti/How-to-Understand-Streams-in-NodeJS/pull/2/commits/cdee249f506019e5247555598b670be7b9ef68e4).

If you want I can commit these in separate PR's, so that you can merge them easily. :)

**Comment by davidgatti** [comment]
@me-shaon you are right on the money with the `const` thing, so in this code for example there is no point of using that, because there is no danger of someone switching where a variable points to :) 

about the other stuff, please submit it, as a new PR. And just focus on typos, name variable if you think they could have more meaning etc. that is no problem, just don't change the style of the code article :)

**Comment by me-shaon** [comment]
Ok, thanks. :)

**Pull request closed without merging**
